---
version: "3"

vars:
  DOTFILES_DIR:
    sh: chezmoi source-path

tasks:
  default:
    silent: true
    cmds:
      - chezmoi {{.CLI_ARGS}}
  code:
    silent: true
    # dir: /{{.PWD}}/{{ relPath .PWD .DOTFILES_DIR }}
    cmds:
      - echo '{{ . | spew }}'
      - pwd
